### ISSUE TITLE
COVID_model fails at instantiation

### ISSUE THREAD

**Issue by kdhansen** [metalcorebear/COVID-Agent-Based-Model#4]
Running `run.py` throw an error.

```
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    meme_model = COVID_model()
  File "C:\Users\Karl Hansen\Documents\Code\mason_covid\model.py", line 20, in __init__
    super().__init__(Model)
TypeError: __init__() takes 1 positional argument but 2 were given
```
Removing `Model` in Line 20 in `super().__init__(Model)`, fixes it.

**Comment by kdhansen** [comment]
This seems to come from me using the mesa 0.8.6 from PyPI. Installing master from github solves this.
